# See http://docs.travis-ci.com/user/languages/julia/ and https://juliadocs.github.io/Documenter.jl/stable/man/hosting/#Hosting-Documentation-1
# See status of Travis builds at https://travis-ci.org/probcomp/GenTF

language: julia

os:
    - linux

julia:
  - 1.0

before_install:
    - sudo ./install_tensorflow.sh

script:
    - julia -e 'ENV["PYTHON"] = "/home/travis/build/probcomp/GenTF/tf_env/bin/python3"; using Pkg; Pkg.build("PyCall"); Pkg.test()'
