# See http://docs.travis-ci.com/user/languages/julia/ and https://juliadocs.github.io/Documenter.jl/stable/man/hosting/#Hosting-Documentation-1
# See status of Travis builds at https://travis-ci.org/probcomp/GenTF

language: julia

os:
    - linux

julia:
  - 1.0

jobs:
  include:
    - stage: test
      before_install:
        - sudo ./install_tensorflow.sh
      script:
        - julia -e 'ENV["PYTHON"] = "/home/travis/build/probcomp/GenTF/tf_env/bin/python3"; using Pkg; Pkg.build("PyCall"); Pkg.test()'
    - stage: docs
      julia: 1.0
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg;
                                    Pkg.add("https://github.com/probcomp/Gen");
                                    Pkg.develop(PackageSpec(path=pwd()));
                                    Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
