# See http://docs.travis-ci.com/user/languages/julia/ and https://juliadocs.github.io/Documenter.jl/stable/man/hosting/#Hosting-Documentation-1
# See status of Travis builds at https://travis-ci.org/probcomp/GenTF

language: julia
os:
    - linux
julia:
  - 1.0
env:
    - CONDA_JL_VERSION="2" PYTHON=""
    - CONDA_JL_VERSION="3" PYTHON=""
notifications:
    email: false
script:
    - julia -e 'using Pkg; Pkg.build("TensorFlow"); Pkg.test()'
matrix:
  allow_failures:
    - env: CONDA_JL_VERSION="3" PYTHON=""
