name = "GenTF"
uuid = "81148d24-ab32-11e8-11fa-fb6cea9195aa"
authors = ["Marco Cusumano-Towner <imarcoam@gmail.com>"]
version = "0.1.0"

[deps]
Gen = "ea4f424c-a589-11e8-07c0-fd5c91b9da4a"
TensorFlow = "1d978283-2c37-5f34-9a8e-e9c0ece82495"

[compat]
Gen = "0.1.0"
TensorFlow = "0.10.1"
